version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: data_pragyan_mariadb_prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_prod_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backups:/backups  # For database backups
    networks:
      - data_pragyan_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=1000

  data-pragyan:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: data_pragyan_app_prod
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mariadb:3306/${MYSQL_DATABASE}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gemini-1.5-flash}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.1}
      - ENVIRONMENT=production
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - uploads_prod_data:/app/uploads
      - logs_prod_data:/app/logs
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - data_pragyan_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  nginx:
    image: nginx:alpine
    container_name: data_pragyan_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - logs_prod_data:/var/log/nginx
    depends_on:
      - data-pragyan
    networks:
      - data_pragyan_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database backup service
  db-backup:
    image: mariadb:10.11
    container_name: data_pragyan_backup
    environment:
      MYSQL_PWD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh:ro
    depends_on:
      - mariadb
    networks:
      - data_pragyan_network
    restart: "no"
    command: >
      sh -c "
      while true; do
        sleep 86400  # Wait 24 hours
        /backup.sh
      done"

volumes:
  mariadb_prod_data:
    driver: local
  uploads_prod_data:
    driver: local
  logs_prod_data:
    driver: local

networks:
  data_pragyan_network:
    driver: bridge