#!/bin/bash

# Script to help capture application screenshots
# This script provides instructions for manual screenshot capture

echo "📸 Data Pragyan Screenshot Capture Guide"
echo "========================================"
echo ""
echo "1. Start the application:"
echo "   docker-compose up -d"
echo "   OR"
echo "   poetry run streamlit run src/app.py --server.port 8503"
echo ""
echo "2. Open browser: http://localhost:8503"
echo ""
echo "3. Capture these screenshots and save them in docs/images/:"
echo ""
echo "   📋 Required Screenshots:"
echo "   ├── main-dashboard.png         (Main interface/homepage)"
echo "   ├── schema-browser.png         (Database schema exploration)"
echo "   ├── natural-language-query.png (Query input interface)"
echo "   ├── sql-generation.png         (Generated SQL display)"
echo "   ├── query-results.png          (Results table)"
echo "   ├── data-visualization.png     (Charts and graphs)"
echo "   ├── file-upload.png            (File upload interface)"
echo "   └── data-processing.png        (File processing preview)"
echo ""
echo "4. Screenshot Tips:"
echo "   • Use full browser window (hide bookmarks bar)"
echo "   • Ensure good contrast and readability"
echo "   • Show realistic data examples"
echo "   • Capture error states for troubleshooting docs"
echo "   • Use consistent browser/OS for uniform appearance"
echo ""
echo "5. Recommended Tools:"
echo "   • macOS: Cmd+Shift+4 (area selection)"
echo "   • Windows: Snipping Tool or Win+Shift+S"
echo "   • Linux: gnome-screenshot or flameshot"
echo ""
echo "6. After capturing, commit and push:"
echo "   git add docs/images/"
echo "   git commit -m 'docs: add application screenshots'"
echo "   git push"
echo ""
echo "The README.md file has been updated with screenshot placeholders."
echo "Replace the placeholder images with your actual screenshots."